config/routes.rb
Rails.application.routes.draw do

  root 'landings#index'
  get 'landings/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'users/:id', to: "users#show", as: 'user'
  resources :users do
    resources :courses do
      member do
        get 'add'
      end
      resources :mods
    end
  end
  get 'courses/:id' => 'courses#view', as: 'view'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  	@courses = Course.last(4).reverse
  end
end

app/helpers/landings_helper.rb
module LandingsHelper
	#To handle SignUp and Login Forma placement anywhere in App Views
  def resource_name
    :user
  end

  def resource_class
  	User
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/landings/index.html.erb
<div class="landing-content">
	<div class="landing-overlay"></div>
	<div class="row">
		<div class="landing-info col-lg-8">
			<center>
				<h1>Impact Society Better</h1>
				<p>Sign Up to learn the Social Entrepreneurship Path <br>from Industry leaders, Social Veterans, Academicians <br>and Entrepreneurs who have been there and done it.</p>
			</center>
		</div>
		<div class="landing-form col-lg-4">
			<% if current_user.present? %>
				<center><%= link_to 'Your Classroom', user_path(current_user.id), class: "btn btn-primary btn-dir" %></center>
			<% else %>
				<div class="landing-action">
					<div class="landing-signup">
						<%= simple_form_for(resource, as: resource_name, url: registration_path(resource), html: {class: "form-horizontal form-user"}) do |f| %>
						  <%= devise_error_messages! %>

						  <div class="form-group">
						  	<%= f.label :first_name, "", class: "control-label col-md-4" %>
						    <div class="col-md-8">
						      <%= f.input_field :first_name, :placeholder => 'First Name', class: "text-field form-control", html: {spellcheck: "false"} %>
						    </div>
						  </div>


						  <div class="form-group">
						  	<%= f.label :last_name, "", class: "control-label col-md-4" %>
						    <div class="col-md-8">
						      <%= f.input_field :last_name, :placeholder => 'Last Name', class: "text-field form-control", html: {spellcheck: "false"} %>
						    </div>
						  </div>
						  
						  <div class="form-group">
						  	<%= f.label :email, class: "control-label col-md-4" %>
						    <div class="col-md-8">
						      <%= f.email_field :email, :placeholder => 'E-mail', class: "text-field form-control", html: {spellcheck: "false"} %>
						    </div>
						  </div>
						    
						  <div class="form-group">
						  	<%= f.label :password, class: "control-label col-md-4" %>
						    <div class="col-md-8">
						      <%= f.password_field :password, :placeholder => 'Enter Password', class: "text-field form-control", html: {autocomplete: "off"} %>
						    </div>
						  </div>
						     
						  <div class="form-group">
						  	<%= f.label :password_confirmation, "", class: "control-label col-md-4" %>
						    <div class="col-md-8">
						      <%= f.password_field :password_confirmation, :placeholder => 'Password Again', class: "text-field form-control", html: {autocomplete: "off"} %>
						    </div>
						  </div>
						     
						  <div class="form-group">
						    <div class="col-md-8">
						      <%= f.submit "Sign Up", class: "btn btn-primary" %>
						    </div>
						  </div>

						  <div class="form-group">
							<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
							  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
							<% end -%>
							<%- if devise_mapping.omniauthable? %>
							  <%- resource_class.omniauth_providers.each do |provider| %>
							    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
							  <% end -%>
							<% end -%>
						  </div>

						<% end %>								
					</div>

					<div class="landing-card">
						<strong><p>New to CuratorsU?</p></strong>
						<p><small>Sign up to take a Course</small></p>
						<button class="btn btn-primary btn-switch">Sign Up</button>
					</div>				
				</div>
			<% end %>
		</div>
	</div>
</div>
<!-- Place in a Featured Course section -->
<!-- <div class="container row" id="fcs">
	<div class="fcs">
	  <% @courses.each do |course| %>
		<div class="col-lg-6 col-md-6 col-sm-6">
			<div class="featured-course">
			<%= link_to view_path(id: course.id ) do %>
				<%= image_tag course.image.normal.url%>
				<div class="name">
					<h2><strong><%= course.name %></strong></h2>	
				</div>
			<% end %>
			</div>
			<div></div>
		</div>
	  <% end %>
	</div>
</div> -->