config/routes.rb
Rails.application.routes.draw do

  root 'landings#index'
  get 'landings/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'users/:id', to: "users#show", as: 'user'
  resources :users do
    resources :courses do
      member do
        get 'add'
      end
      resources :mods
    end
  end
  get 'courses/:id' => 'courses#view', as: 'view'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/views/elements/_footer.html.erb
    <!--=========== BEGIN FOOTER SECTION ================-->
    <footer id="footer">
      <!-- Start footer top area -->
      <div class="footer_top">
        <div class="container">
          <div class="row">
            <div class="col-ld-4  col-md-4 col-sm-4">
              <div class="single_footer_widget">
                <h3>Latest Courses</h3>
                <% unless @courses.blank? %>
                  <% @courses.each do |course|%>
                    <p><%= link_to course.name, view_path(id: course.id )%></p>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="col-ld-4  col-md-4 col-sm-4">
              <div class="single_footer_widget">
                <h3>Community</h3>
                <ul class="footer_widget_nav">
                  <li><a href="http://curators.ng/#section-200">Learning Tracks</a></li>
                  <li><a href="http://curators.ng/#section-28">Open Workshops</a></li>
                  <li><a href="http://curators.ng/#section-81">Initiatives</a></li>
                  <li><a href="http://curators.ng/#section-34">Thought Leadership</a></li>
                </ul>
              </div>
            </div>
<!--             <div class="col-ld-3  col-md-3 col-sm-3">
              <div class="single_footer_widget">
                <h3>Partner Links</h3>
                <ul class="footer_widget_nav">
                  <li><a href="#">Link 1</a></li>
                  <li><a href="#">Link 2</a></li>
                  <li><a href="#">Link 3</a></li>
                  <li><a href="#">Link 4</a></li>
                  <li><a href="#">Link 5</a></li>
                </ul>
              </div>
            </div> -->
            <div class="col-ld-4  col-md-4 col-sm-4">
              <div class="single_footer_widget">
                <h3>Social Links</h3>

                  <a href="https://www.facebook.com/curatorsu"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
                  <a href="https://twitter.com/curatorsu"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>                  
                  <a href="mailto:info@curators.ng"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>

              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- End footer top area -->

      <!-- Start footer bottom area -->
      <div class="footer_bottom">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="footer_bootomLeft">
                <p> Copyright &copy; All Rights Reserved</p>
              </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="footer_bootomRight">
                <p>Designed by <a href="http://curators.ng" rel="nofollow"> Curators Uni</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- End footer bottom area -->
    </footer>
    <!--=========== END FOOTER SECTION ================--> 

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag("culogo.png"), root_path, class: "navbar-brand" %>
  </div>
  <% url = "http://#{request.host+request.fullpath}" %>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li> <%= link_to 'MY CLASSROOM', user_path(current_user.id) %> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">ACCOUNT <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= simple_form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
                <div class="form-group">
                  <%= f.text_field :email, :placeholder => "Email", class: "form-control" %> 
                </div>
                <div class="form-group">
                  <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
                </div>
                <div class="checkbox">
                  <%= f.check_box :remember_me %><%= f.label :remember_me %>
                </div>
                <%= f.submit 'Login', class: "btn btn-default" %>
            <% end %>
          </li>       
        <% end %>               
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>