config/routes.rb
Rails.application.routes.draw do

  root 'landings#index'
  get 'landings/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'users/:id', to: "users#show", as: 'user'
  resources :users do
    resources :courses do
      member do
        get 'add'
      end
      resources :mods
    end
  end
  get 'courses/:id' => 'courses#view', as: 'view'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:view, :show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @courses = Course.all
  end

  def view
    @course = Course.find(params[:id])  
  end

  # GET /courses/new
  def new
    @course = Course.new
    @courses = Course.all
  end

  # GET /courses/1/edit
  def edit
  end

  def add
     @user = User.find(params[:user_id])
     @courses = Course.all
     @course = Course.find(params[:id])
      if @user.courses.include? @course
       redirect_to user_course_mods_path(course_id: @course.id), notice: 'Already Enrolled.'
      else
       @course.users << @user
       redirect_to user_course_mods_path(course_id: @course.id), notice: 'You are now Enrolled for this course.' 
     end
  end

  # POST /courses
  # POST /courses.json


  def create
    authorize! :create, Course
    @courses = Course.all
    @course = Course.new(course_params)
    @course.users << User.find(params[:user_id])
    respond_to do |format|
      if @course.save
        format.html { render :show, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    authorize! :update, Course
    respond_to do |format|
      if @course.update(course_params)
        format.html { render :show, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    authorize! :destroy, @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=begin
  def reg_course
    redirect_to :action => 'set_course'
    current_user.courses << @course
    respond_to do
      redirect_to :action => 'show'
    end
  end
=end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
      @courses = Course.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :timeline, :instructors, :image)
    end


end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
   <div class="form-group">
    <%= f.label :name, class: "control-label col-md-4" %>
    <div class="col-md-8">
      <%= f.input_field :name, class: "text-field form-control", html: {spellcheck: "false"} %>
    </div>
  </div>
  <div>
  	<%= f.label :description, class: "control-label col-md-4" %>
    <div class="col-md-8">
      <%= f.input_field :description, class: "text-area form-control", html: {spellcheck: "true"} %>
    </div>
  </div>
  <div class="input-daterange" data-behaviour="datepicker" id="datepicker" data-date-format="dd/mm/yyyy">
  	<%= f.label :from, class: "control-label col-md-4" %>
    <div class="col-md-8">
      <%= f.date_field :timeline, class: "text-field form-control timeline","data-provide" => 'datepicker' %>
    </div>
    <%= f.label :to, class: "control-label col-md-4" %>
    <div class="col-md-8">
      <%= f.date_field :timeline_to, class: "text-field form-control timeline","data-provide" => 'datepicker' %>
    </div>     	
  </div>
  <div>
  	<%= f.label :instructors, class: "control-label col-md-4" %>
    <div class="col-md-8">
      <%= f.input_field :instructors, class: "text-field form-control", html: {spellcheck: "false"} %>
    </div>    	
  </div>
  <div>
    <%= f.label :image, class: "control-label col-md-4" %>
    <div class="field col-md-8">
      <%= f.file_field :image %>
    </div>
  </div>    
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

app/views/courses/edit.html.erb
<div class="yielder container">	
	<h1>Editing course</h1>
	<%= simple_form_for @course, url: {action: 'update', multipart: true} do |f| %>
	  <%= f.error_notification %>
	  <%= render 'form', f: f %>
	<% end %>

	<%= link_to 'Show Course', user_course_path(id: @course.id) %>
	<%= link_to 'Back', :back %>
</div>

app/views/courses/index.html.erb
<div class="yielder container">
<!--   <div class="filter col-lg-3">
    
  </div> 
  TODO
  Add Filter and Search Functionailty here.
  -->
<!--   <div class="all-courses col-lg-9"> -->
    <div class="row">
      <% @courses.each do |course| %>
            <!-- start single course -->
            <div class="col-lg-4 col-md-4 col-sm-6">
              <div class="single_course wow fadeInUp">
                <div class="singCourse_imgarea">
              <%= image_tag course.image.normal.url %>
                  <div class="mask">                         
                    <%= link_to 'View Course', user_course_path(id: course.id ), class:"course_more" %>
                  </div>
                </div>
                <div class="singCourse_content">
                <h3 class="singCourse_title"><%= link_to course.name, user_course_path(id: course.id) %></h3>
                <p class="singCourse_price"><span>$20</span> </p>
                <p><%= course.description%></p>
                <p><strong><%= course.timeline %></strong></p>
                </div>
                <div class="singCourse_author">
                  <!-- <img src="img/author.jpg" alt="img"> -->
                  <p>Instructor(s): <%= course.instructors%></p>
                </div>
                  <% if current_user.role == "curator" %>
                    <%= link_to 'Edit Course Information', edit_user_course_path(id: course.id), class: "btn btn-primary" %>
                  <% end %>                
              </div>
            </div>
            <!-- End single course -->
        <% end %>      
    </div>  
<!--   </div> -->

</div>

app/views/courses/new.html.erb
<div class="yielder">
	<h1>New course</h1>
	<%= simple_form_for(@course, url: user_courses_path, html: {method: :post, multipart: true}) do |f| %>
	  <%= f.error_notification %>
	  <%= render 'form', f: f %>
	<% end %>
<%= link_to 'Back', :back %>
</div>

app/views/courses/show.html.erb
<div class="yielder container">
<% @user ||= current_user %>
	<div class="course-info">
		<div class="course-header row">
			<h1> <%= @course.name %> </h1>
			<h5> <%= @course.description %> </h5>
		</div>

<!-- Show First Introductory Video on Course Page -->
		<div class="course-subhead row">
	  		<div class="col-lg-9 col-md-9 col-sm-12">
	  			<%if @course.mods.present? %>
	  				<%= embed_video(@course.mods.first.video) %>
	  			<% else %>
	  				<%= image_tag @course.image.large.url :class => "course-img img-responsive" %>
	  			<% end %>
	  		</div>
	  		<div class="course-action col-lg-3 col-md-12 col-sm-12">
	  		  	<p> <strong>Duration: </strong> <br> <%= @course.timeline %> </p>
	  		  	<p> <strong> Instructor(s): </strong> <br> <%= @course.instructors %> </p>
	  		  	<p> <strong>Lectures:</strong><br> 
	  		  	<% if @course.mods.nil? %>
	  		  		<p>No Course Modules added yet</p>
	  		  	<% else %>
	  		  		<p> contains <%= @course.mods.count %> Module(s) </p>
	  		  	<% end %>
		  	   <% if can? :create && :update, Mod %>
				<%= link_to 'Back', :back, class: "btn btn-primary" %><br>
				<%= link_to 'Edit Course Details', edit_user_course_path(id: @course.id), class: "btn btn-primary" %><br>
				<%= link_to 'Add New Module', new_user_course_mod_path(course_id: @course.id), class: "btn btn-primary"%><br>
				<%= link_to 'Test the Course', add_user_course_path(id: @course.id), class: "btn btn-primary" %>
			   <% else %>
				<%= link_to 'Start Course here!', add_user_course_path(course_id: @course.id), class: "btn btn-primary" %>
			   <% end %>
	  		</div>

		</div>
	</div>	 
</div>

app/views/courses/view.html.erb
<div class="yielder container">
<% @user ||= current_user %>
	<div class="course-info">
		<div class="course-header row">
			<h1> <%= @course.name %> </h1>
			<h5> <%= @course.description %> </h5>
		</div>

<!-- Show First Introductory Video on Course Page -->
		<div class="course-subhead row">
	  		<div class="col-lg-9 col-md-9 col-sm-12">
	  			<%if @course.mods.present? %>
	  				<%= embed_video(@course.mods.first.video) %>
	  			<% else %>
	  				<%= image_tag @course.image.large.url :class => "course-img img-responsive" %>
	  			<% end %>
	  		</div>
	  		<div class="course-action col-lg-3 col-md-12 col-sm-12">
	  		  	<p> <strong>Duration: </strong> <br> <%= @course.timeline %> </p>
	  		  	<p> <strong> Instructor(s): </strong> <br> <%= @course.instructors %> </p>
	  		  	<p> <strong>Lectures:</strong><br> 
	  		  	<% if @course.mods.nil? %>
	  		  		<p>No Course Modules added yet</p>
	  		  	<% end %>
	  		  	<% if current_user.present? %>
					<%= link_to 'Start Course here!', add_user_course_path(course_id: @course.id, user_id: @user.id), class: "btn btn-primary" %>
				<% else %>
					<%= link_to 'Sign Up to take this Course', new_user_registration_path, class: "btn btn-primary" %>
				<% end %>
			   
	  		</div>

		</div>
	</div>	 
</div>